#!/usr/bin/env python3
"""Dev bot main loop — Python Agent SDK version."""

import argparse
import asyncio
import logging
import os
import signal
import sys
import time
from pathlib import Path

from dotenv import load_dotenv
from filelock import FileLock, Timeout

from .agent import run_cycle
from .config import ALLOWED_TOOLS, Config, load_config, load_mcp_servers, sanitize_env
from .costs import record_cost

SCRIPT_DIR = Path(__file__).resolve().parent.parent
DATA_DIR = SCRIPT_DIR / "data"


def _resolve_path(p: str) -> str:
    """Resolve a path that may be relative to SCRIPT_DIR, ~, or absolute."""
    path = Path(p).expanduser()
    if not path.is_absolute():
        path = SCRIPT_DIR / path
    return str(path.resolve())


def setup_ssh(script_dir: Path) -> None:
    """Generate SSH config from env vars and set GIT_SSH_COMMAND.

    Reads BOT_SSH_KEY (for github.com) and GITLAB_SSH_KEY (for gitlab)
    from the environment. Skips if neither is set.
    """
    bot_key = os.environ.get("BOT_SSH_KEY")
    gitlab_key = os.environ.get("GITLAB_SSH_KEY")

    if not bot_key and not gitlab_key:
        # No keys configured — check if there's an existing SSH config
        # in the project dir (e.g. committed to the repo) and use it.
        fallback = ssh_dir / "config" if (ssh_dir := script_dir / ".ssh").exists() else None
        if fallback and fallback.exists():
            os.environ["GIT_SSH_COMMAND"] = f"ssh -F {fallback}"
        return

    ssh_dir = script_dir / ".ssh"
    ssh_dir.mkdir(exist_ok=True)
    config_path = ssh_dir / "config"

    lines = ["# Auto-generated by bot/run.py — do not edit manually"]

    if bot_key:
        lines += [
            "",
            "Host github.com-bot",
            "  HostName github.com",
            "  User git",
            f"  IdentityFile {_resolve_path(bot_key)}",
            "  IdentitiesOnly yes",
            "  StrictHostKeyChecking accept-new",
        ]

    if gitlab_key:
        lines += [
            "",
            "Host gitlab.cee.redhat.com",
            f"  IdentityFile {_resolve_path(gitlab_key)}",
            "  IdentitiesOnly yes",
            "  StrictHostKeyChecking accept-new",
        ]

    config_path.write_text("\n".join(lines) + "\n")
    config_path.chmod(0o600)
    os.environ["GIT_SSH_COMMAND"] = f"ssh -F {config_path}"


def setup_git(script_dir: Path) -> None:
    """Generate a .gitconfig with identity and optional GPG signing.

    Reads from env: GIT_AUTHOR_NAME, GIT_AUTHOR_EMAIL, GPG_SIGNING_KEY.
    Sets GIT_CONFIG_GLOBAL so all repos use this config.
    """
    name = os.environ.get("GIT_AUTHOR_NAME")
    email = os.environ.get("GIT_AUTHOR_EMAIL")

    if not name and not email:
        return

    config_path = script_dir / ".gitconfig"
    lines = [
        "# Auto-generated by bot/run.py — do not edit manually",
        "[user]",
    ]
    if name:
        lines.append(f"\tname = {name}")
    if email:
        lines.append(f"\temail = {email}")

    signing_key = os.environ.get("GPG_SIGNING_KEY")
    if signing_key:
        lines += [
            f"\tsigningkey = {signing_key}",
            "[commit]",
            "\tgpgsign = true",
            "[gpg]",
            "\tformat = openpgp",
        ]

    config_path.write_text("\n".join(lines) + "\n")
    os.environ["GIT_CONFIG_GLOBAL"] = str(config_path)


def setup_logging() -> None:
    """Configure logging to stdout and data/bot.log."""
    DATA_DIR.mkdir(exist_ok=True)
    fmt = "[%(asctime)s] %(message)s"
    datefmt = "%Y-%m-%d %H:%M:%S"

    handlers: list[logging.Handler] = [
        logging.StreamHandler(sys.stdout),
        logging.FileHandler(DATA_DIR / "bot.log", mode="a"),
    ]

    logging.basicConfig(
        level=logging.INFO,
        format=fmt,
        datefmt=datefmt,
        handlers=handlers,
    )


def main() -> None:
    # Load .env before anything else so MCP servers get the credentials
    load_dotenv(SCRIPT_DIR / ".env")

    # Resolve GOOGLE_APPLICATION_CREDENTIALS to absolute path so the SDK
    # finds the service account key regardless of working directory
    gac = os.environ.get("GOOGLE_APPLICATION_CREDENTIALS")
    if gac and not os.path.isabs(gac):
        os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = str(SCRIPT_DIR / gac)

    # Set up SSH and git identity from env vars (no-op if not configured)
    setup_ssh(SCRIPT_DIR)
    setup_git(SCRIPT_DIR)

    parser = argparse.ArgumentParser(description="Dev bot agent loop")
    parser.add_argument(
        "--label",
        required=True,
        help="Primary Jira label (e.g. hcc-ai-framework)",
    )
    parser.add_argument(
        "--instance-id",
        default=os.environ.get("BOT_INSTANCE_ID", ""),
        help="Bot instance ID for multi-instance isolation (default: $BOT_INSTANCE_ID)",
    )
    args = parser.parse_args()

    setup_logging()
    logger = logging.getLogger(__name__)

    config = load_config(SCRIPT_DIR)
    mcp_servers = load_mcp_servers(SCRIPT_DIR)

    # Remove secrets from env so Bash subprocesses can't leak them.
    # MCP servers already have resolved values. gh/glab use config files.
    sanitize_env()
    logger.info("Sanitized environment — secrets removed from env vars.")

    # Lock file — prevent concurrent runs
    lock = FileLock(DATA_DIR / ".lock", timeout=0)
    try:
        lock.acquire()
    except Timeout:
        logger.error("Another instance is running. Exiting.")
        sys.exit(1)

    def shutdown(sig, frame):
        logger.info("Shutting down.")
        lock.release()
        sys.exit(0)

    signal.signal(signal.SIGINT, shutdown)
    signal.signal(signal.SIGTERM, shutdown)

    instance_id = args.instance_id or None
    logger.info(
        "Dev bot started. Label: %s. Instance: %s. Provider: Vertex AI. Active interval: %ds. Idle interval: %ds.",
        args.label,
        instance_id or "(none)",
        config.interval,
        config.idle_interval,
    )

    try:
        while True:
            logger.info("Running agent cycle...")

            result, ctx = asyncio.run(
                run_cycle(
                    label=args.label,
                    config=config,
                    mcp_servers=mcp_servers,
                    allowed_tools=ALLOWED_TOOLS,
                    cwd=str(SCRIPT_DIR),
                    instance_id=instance_id,
                )
            )

            if result is not None:
                no_work = record_cost(
                    costs_file=DATA_DIR / "costs.jsonl",
                    label=args.label,
                    result=result,
                    ctx=ctx,
                )
            else:
                no_work = False
                logger.warning("Cycle produced no result")

            if no_work:
                logger.info(
                    "No work found. Sleeping for %ds...", config.idle_interval
                )
                time.sleep(config.idle_interval)
            else:
                logger.info(
                    "Cycle complete. Sleeping for %ds...", config.interval
                )
                time.sleep(config.interval)
    finally:
        lock.release()
